### ISSUE TITLE
Property support blender output with period in Cryptomatte names

### ISSUE THREAD

**Issue by jonahfriedman** [Psyop/Cryptomatte#104]
As seen in this ticket: 

https://developer.blender.org/T57745

**Comment by jonahfriedman** [comment]
Fixed in 1.2.4 (but not tested with actual Nuke output, only mocked up with modify metadata)

**Comment by lukasstockner** [comment]
Here's a Blender/Cycles render of the 2.77 splash screen [(source)](https://www.blender.org/download/demo-files/) containing Cryptomattes for testing:
[blender_cryptomatte_example.zip](https://github.com/Psyop/Cryptomatte/files/2898577/blender_cryptomatte_example.zip)

**Comment by caelunshun** [comment]
Still only appears to work with Blender when the view layer is renamed to "scene." This should probably be fixed.

**Comment by karlisstigis** [comment]
Are there any news? It still doesn't work.

**Comment by jonahfriedman** [comment]
It was fixed as of 1.2.4, which was months ago. 

In the release notes: Fixed gizmo for Blender channel names containing "." which get converted to underscores in Nuke, also fixed for Encryptomatte. (#104)

Could you confirm you're using that version, and send an EXR file that doesn't work in it?

**Comment by karlisstigis** [comment]
@jonahfriedman 
Hey, we solved the issue by following a suggestion here:
https://github.com/Psyop/Cryptomatte/issues/19

When rendering straight to multipass exr without Compositing, everything works, but the problem appears when using Compositing, because the exr file doesn't get the needed metadata.
This is not great, because you really want a way to render your layers in seperate files and not one huge megafile. :) 

Although the issue basically is fixed by using the "ModifyMetaData" node in Nuke,
I think it would be much nicer if the file just worked. The solution would be to include the same MetaData in exr file at least one cryptomatte channel is connected to file output node. I don't know, maybe there is a more elegant solution.
