### ISSUE TITLE
Selecting objects behind transparency in nuke

### ISSUE THREAD

**Issue by oumad** [Psyop/Cryptomatte#11]
When I try to select an object with the color picker behind transparency I can only get the foreground object and never the one behind. 
Is there a way to select objects behind transparent other objects without having to go to the 3d scene to get the exact name of the shape ?

**Comment by jonahfriedman** [comment]
Hi,

When you key something, it actually just uses the blue channel of whatever color you're selecting. The Cryptomatte gizmo shuffles the **most significant** ID into the blue channel, so if your front transparent object is the most significant contributor to the pixel that's what you get.

The images are layed out like this:

crypto_object00.r - ID 1
crypto_object00.g - Coverage 1
crypto_object00.b - ID 2
crypto_object00.a - Converage 2

So if you view and key the crypto_object00 image instead of the output of the gizmo, the blue channel is the second most important ID, and you can key that instead, selecting the second most important object in the pixel instead.

**Comment by oumad** [comment]
Yes that works ! Thank you ! it is actually able to select something behind 2 transparent objects.
