### ISSUE TITLE
[Nuke] Not seeing any output

### ISSUE THREAD

**Issue by brian5x5** [Psyop/Cryptomatte#112]
I've installed Cryptomatte following the instructions but I must be doing something wrong.  I'm using the supplied test images and don't see anything when I attach the gizmo.  I've tried deleting everything and starting over.  I've tried installing on Mac and Linux but they both act the same.  Troubleshooting says:

"Something went wrong. If you would like to report this, please the text in this window: 
Error Traceback: 
Traceback (most recent call last):
  File "", line 4, in 
  File "/Users/brian/.nuke/cryptomatte_utilities.py", line 803, in troubleshoot_gizmo
    issues = _troubleshoot_gizmo(node) + _troubleshoot_setup()
  File "/Users/brian/.nuke/cryptomatte_utilities.py", line 797, in _troubleshoot_setup
    issues.append(BAD_INSTALL)
NameError: global name 'BAD_INSTALL' is not defined"

![Screen Shot 2019-07-09 at 12 34 15 PM](https://user-images.githubusercontent.com/9296812/60917571-22658600-a246-11e9-8360-4c4914d5a784.png)

**Comment by jonahfriedman** [comment]
Well, that's embarrassing. The issue is with your installation. I'll fix the message, in the next bug fix, but until you get that maybe try re-installing? The message would have said, 

> Installation is wrong, callbacks were not found. setup_cryptomatte() did not run, init.py may not be set up properly.

Please feel free to reopen this if following the installation instructions and setting up init.py does not fix the issue for you.
