### ISSUE TITLE
mmh3 error causes Cryptomatte expression to remain empty

### ISSUE THREAD

**Issue by mazevfx** [Psyop/Cryptomatte#118]
Hi, 

I've an issue with an EXR sequence rendered out of Houdini with Arnold. 
When I bring it into Nuke and plug in a Cryptomatte it first behaves as expected, finding that it is material based and the pass looks fine. 
But when I use the picker and select a color, nothing happens next - it simply doesn't register the selection even though everything else seems correct, it even finds the name and path of the material as you can see. 

Any thoughts on what could be the issue? Time is a factor here so any and all swift help would be really appreciated! 

And thanks for creating the tool to start with, I've used it at work with great pleasure! 

Cheers, 

Jack

![nukeissue_01](https://user-images.githubusercontent.com/55650929/65384818-2ffbb980-dd27-11e9-9f2e-428761b64907.JPG)
![nukeissue_02](https://user-images.githubusercontent.com/55650929/65384819-2ffbb980-dd27-11e9-91f5-ba78fb0f7978.JPG)

**Comment by filmkorn** [comment]
Hi Jack, You seem to have a different mmh3 module installed somewhere. To confirm run the following in script editor:
```
import mmh3
print mmh3.__file__
```
This should print the filepath of the conflicting mmh3 module. If you're able to remove/ rename this module, cryptomatte should be able to fall back to it's own pymmh3 module and work again.

Mitja

**Comment by jonahfriedman** [comment]
Hi @mazevfx  - any update on this? @filmkorn is on the money about where to look first here.

**Comment by jonahfriedman** [comment]
According to this the issue appears solved: https://community.foundry.com/discuss/topic/149424/cryptomatte-issue-urgent

I was not able to get mmh3 working on my end in Nuke, I believe the issue was mismatching MSVC versions. Given that this seems to be solved I'm going to close this now, but feel free to reopen if it isn't. 

@mazevfx  - if you would like to run the tests yourself with your mmh3 installed, please use the following in your Nuke script editor. If there are any issues (and you're on the newest version), please feel free to reopen this to report them. 

```
import cryptomatte_utilities as cu
cu.tests.run_nuke_tests()
```

**Comment by mazevfx** [comment]
Hi Jonah and Mitja, 

Sorry for not replying here, it slipped my mind after I got help on the Foundry forum but it has been solved! Thank you for the help!
