### ISSUE TITLE
(Colored) transparency

### ISSUE THREAD

**Issue by vkoylazov** [Psyop/Cryptomatte#12]
Hello,

Not sure this is the best place to ask, if there is a better place, please let me know.

Is there a document describing how a renderer should generate weights for

a) transparent objects (i.e. does the weight include the transparency of the object) - my guess is "yes", but I'd like to confirm;

b) objects behind other transparent objects (i.e. should the weight take into account any attenuation by transparent objects in front of the selected one) - my guess is "yes", but I'd like to confirm;

c)  if the answer to b) is "yes", how is colored transparency handled?

Best regards,
Vlado

**Comment by jonahfriedman** [comment]
Hi Vlado! I think this is a perfectly good place to discuss this. Another option would be the Cryptomatte Committee e-mail list, though that's not being used very much. 

> Is there a document describing how a renderer should generate weights

The specification in this repo is really only about how the EXR file is encoded and less what the renderer does, but our [poster](https://github.com/Psyop/Cryptomatte/blob/master/specification/IDmattes_poster.pdf) does describe what happens in the renderer (though the specification is newer and supersedes it). 

> a) transparent objects (i.e. does the weight include the transparency of the object) - my guess is "yes", but I'd like to confirm;

That is correct. Once encoded, transparency is treated as just another case of multiple IDs in a pixel, so the weight does have to include the transparency. This has to happen in the renderer because once encoded, we don't store any information about how there came to be multiple IDs in a pixel.

> b) objects behind other transparent objects (i.e. should the weight take into account any attenuation by transparent objects in front of the selected one) - my guess is "yes", but I'd like to confirm;

Also correct. In our implementation we iterate through the depth samples for a camera sample front to back in the filter, attenuating the available opacity as we go. 

> c) if the answer to b) is "yes", how is colored transparency handled?

We just use an average of the three channels. If we did something else we'd still just be encoding a monochrome matte anyway, so I don't have a better idea. If there's something better to do here, we're definitely interested.

**Comment by vkoylazov** [comment]
Perfect, then I'm done in that regard :) I have one more question about naming conventions for objects, but I will post another issue.

Best regards,
Vlado

**Comment by jonahfriedman** [comment]
Glad to hear it!
