### ISSUE TITLE
Naming conventions for scene objects

### ISSUE THREAD

**Issue by vkoylazov** [Psyop/Cryptomatte#13]
Hello,

Is there a naming convention for objects in the scene? I vaguely remember this being discussed a while ago, but I can't find it right now, so apologies if it's a duplicate.

a) Should I store only the leaf geometry name, the full path from the scene root, or should I provide an option to switch?

b) If I need to store the full name, is there an accepted separator between the object names in the hierarchy? I see that the sample files appear to use '.' but this seems a bit unorthodox compared to '/' or '|'. Should this separator be always included as the first symbol in the path (f.e. "/parent_obj/child_obj" vs "parent_obj/child_obj"?

Best regards,
Vlado

**Comment by jonahfriedman** [comment]
The idea behind the names is to use whatever organizational information is available from the DCC. In our implementation this is largely based on Maya / Softimage organization, which (roughly speaking) organizes things by namespace for references and object names. So this is a bit Maya centric, but any string information can be used however. 

```
myNamespace:myObjectShape
myNamespace:myMaterialName

The following mattes make sense:

namespace: "myNamespace"
object: "myObjectShape"
material: "MyMaterialName"

or optionally, if "strip namespace" options are disabled:

namespace: "myNamespace"
object: "myNamespace:myObjectShape"
material: "myNamespace:MyMaterialName"

```

In a more Katana-style app that doesn't have the explicit namespace / object name distinctions, and everything is just a nested hierarchy, I think something else makes sense:

```
scene/characters/bob/head/tooth1/filling

Should probably be split into "asset" and "object" names like this: 

asset: "scene/characters/bob/"
object: "head/tooth1/filling"

````
So in this app, it'd make sense to have an integer control for where along the object path the names get split by the "/" delimiter. In this case the value would be "3". 

In any case, the goal is to use the pre-existing organization to make mattes that will be the same from scene to scene as much as possible. The "asset|namespace / object / material" mattes are just what made sense in our workflows. Others have created Cryptomattes based on the name of the procedural that generated the objects as well. 

> a) Should I store only the leaf geometry name, the full path from the scene root, or should I provide an option to switch?

We do only the leaf (because this is what's available in Arnold). In cases where the whole hierarchy path is exported in Arnold, Gaetan contributed a patch that strips that to the leaf node as well. I think this is the better way and the right default, since accepted practice in Maya is to have unique names in a namespace anyway, but there would be nothing wrong with providing an option. Also other DCCs have other organizational information. 

> b) If I need to store the full name, is there an accepted separator between the object names in the hierarchy? I see that the sample files appear to use '.' but this seems a bit unorthodox compared to '/' or '|'. Should this separator be always included as the first symbol in the path (f.e. "/parent_obj/child_obj" vs "parent_obj/child_obj"?

This is soley because they were produced from Softimage (and those are instance names). Both '/' and '|' work fine. Using the DCC native delimiters when possible is good I think because it encourages communication between compositing and 3D.

**Comment by jonahfriedman** [comment]
Closing this, but feel free to reopen if there's something to do / add. Thanks!
