### ISSUE TITLE
nuke 7.0 v6

### ISSUE THREAD

**Issue by Tylox81** [Psyop/Cryptomatte#17]
Hi Guys,

is there any chance or any way to cryptomatte works with the v6 version of Nuke 7.0 ?

Regards.

**Comment by acjones** [comment]
Do you have any more details on the problems you're seeing in version 7.0v6?  For example, is it just the typical version compatibility warning, or are you seeing a different problem?

It should be possible to support 7.0v6 in theory, unless we run into something unexpected on the Nuke side.  The plugin is just python and a gizmo, which usually makes version compatibility pretty easy.  The current gizmos reference version 7.0v10, but I want to do some more tests before I vouch for it actually working in that version or anything before it.

**Comment by Tylox81** [comment]
I guess it's just the compatibility...

Here is the error when i select "bunny_CryptoObject.exr" and apply Cryptomatte.

**Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:/Users/---/.nuke\cryptomatte_utilities.py", line 267, in cryptomatte_create_gizmo
    return nuke.createNode("Cryptomatte") 
RuntimeError: C:/Users/---/.nuke/Cryptomatte.gizmo is for nuke7.0v10; this is nuke7.0v6**

I can access to the gizmo but when i take the picker to pick a color on the image, the red and green channel give me a value but not the blue one.
Here's a screeshot below.

![crypto_error](https://user-images.githubusercontent.com/29728729/27628540-a7174ab8-5bef-11e7-8c55-04c61f9b3e77.jpg)

**Comment by acjones** [comment]
Looking at your screenshot, which is referencing "inf", it seems possible you may be hitting the GPU acceleration issue with the color picker.  See the entry in troubleshooting.md, or [this other issue from today](https://github.com/Psyop/Cryptomatte/issues/20).  There should be no floating point signal values in the Cryptomatte hashes, so if you're seeing "inf" it's probably due to some kind of un-wanted type conversion.

I also just did a little testing on 7.0v10 (which is the oldest version I have on hand).  There's actually another bug in the gizmo, which is that it had a reference to "uCryptoObject" in one of the shuffle nodes.  That was causing issues for me in 7.0v10 if the channel didn't already exist.  I removed that reference and am now able to key objects as expected.  I also manually edited the gizmo to indicate 7.0v1, which will hopefully eliminate the version compatibility warnings.

The changes have been pushed up in the "encryptomatte" branch, which is considered beta.  (This includes some other updates, such as the Encryptomatte gizmo and support for sidecar manifests.  We don't have any known issues with those features at this time, but would welcome testing and feedback.  Encryptomatte needs some documentation, but there are tool-tips and the standard "help" text for the node).

**Comment by jonahfriedman** [comment]
Thanks Andy for fixing the compatibility version and the uCryptoObject thing.

@Tylox81, you can download the dev version here. https://github.com/Psyop/Cryptomatte/archive/encryptomatte.zip, or https://github.com/Psyop/Cryptomatte/tree/encryptomatte. 

Closing this.  Feel free to reopen if you have any issues.
