### ISSUE TITLE
Nuke: `mmh3` hashing mismatches with `pymmh3`

### ISSUE THREAD

**Issue by nrusch** [Psyop/Cryptomatte#4]
Nuke 9.0v7 on Fedora 19.

The hash function from the compiled `mmh3` module frequently produces completely different results than the distributed `pymmh3` module, which causes the `cryptomatte_utilities` module to generate bad expressions with a literal "None" in them when certain objects, materials, etc. are picked.

```python
>>> pymmh3.hash('Buddha11|BuddhaShape')
# Result: 3604411835
>>> mmh3.hash('Buddha11|BuddhaShape')
# Result: -690555461
```

I have tested mmh3 2.0 and 2.3.1. Using `pymmh3` seems to work consistently.

**Comment by jonahfriedman** [comment]
Interesting: 2^32 - 690555461 = 3604411835

The code in AlShaders is using the canonical c version of MurmurHash3, and its results seem to always be consistent with pymmh3. I confess we never actually tried the compiled mmh3 module.

There's never a time that requires hashing so many names in Python that it makes much of a difference for user experience, except if you use test_manifest, so using the pure Python hash is totally fine in practice.

**Comment by acjones** [comment]
Did a bit more digging.  It looks like pymmh3 was updated back in March to work like the compiled version.  So the version we packaged is slightly out of date.  Murmur3 doesn't require signed or unsigned interpretation of the 32 bits -- that assumption is just part of the python modules.  Presumably, they chose signed ints for python, because it's the default integer type.

In our case we're not _really_ using signed or unsigned in the specification for how we map the hash values to floats, as we just care about the original bits.  So this should just be a matter of updating to the latest pymmh3 to get the module behaviors back in sync, and then accounting for signed-->unsigned in our mm3hash_float function in cryptomatte_utilities.py instead of relying on pymmh3 to return unsigned.

For now, the simplest workaround should be to not use the compiled mmh3.  Implementing a patch is also probably pretty simple, but as Jonah said, performance isn't particularly critical here.

**Comment by acjones** [comment]
I've pushed up a fix for this in dev.

**Comment by nrusch** [comment]
Thanks for the quick responses guys. I'll give the dev branch a try.

**Comment by nrusch** [comment]
Works as expected now. I'll go ahead and close this.
