### ISSUE TITLE
Cryptomatte Nuke gizmo breaks when made into group

### ISSUE THREAD

**Issue by fredrikaverpil** [Psyop/Cryptomatte#45]
We make all Nuke gizmos into groups so that we can ~~ensure~~ increase probability that the script can be opened exactly as it was created a year or two down the line (for various reasons), even if we do have software version control in place which will properly register the Nuke/Cryptomatte versions etc...

```python
gizmo = nuke.createNode('Cryptomatte')
group = gizmo.makeGroup()
nuke.delete(gizmo)
```

I'm noticing that the Cryptomatte v1.1.4 gizmo breaks when made into a group. Is it possible to avoid this breakage somehow?
Perhaps this cannot be avoided, and if so, that's fine. I just wanted to check.

**Comment by jonahfriedman** [comment]
Hi @fredrikaverpil,

The gizmos should turn into groups that have the same output as the gizmo did. They won't work after that of course, since none of the callbacks keep working. It might be possible to have limited functionality by repeatedly pressing force update, but this really wasn't a use case we planned on so there's no guarantees at all. 

Two things you should know though-

First, we're trying to stay backward compatible. Old 1.4.x scripts open with the 1.2 gizmos just fine. 

Second, for putting Nuke scripts into cold storage where they should continue to work away from the warm light of the plugin, we made "decryptomatte". It replaces the gizmos with some expression nodes.

**Comment by acjones** [comment]
Fredrik, I just wanted to confirm that when you say it "breaks" you mean that you can no longer pull keys -- not that the output of a node that already had keys changes.

Also, an idea:
If you're converting nodes to Groups via a callback, you could probably add some logic to add an additional hidden knob on the groups you're creating with extra info about the class (and version?) of the originating Gizmo.  You could then define "generic" callbacks for the Group class that redirect to the gizmo callbacks by doing lookups in the nuke.callbacks dictionaries based on the info in the hidden knob.  Might actually be a nice addition to whatever system you're using for transmogroupfying your gizmos.

My one fear with this would be the extra overhead on the callbacks, since you'd be relying on python code to filter callbacks by class, instead of the usual mechanism (which I assume is done in C++?).  But that's probably just paranoia, as python is generally pretty fast at this stuff and a lot of Nuke callbacks already basically do something this anyway to provide knob-specific behaviors.

Anyway, that's my unofficial stance.  But the official stance is:  Do not remove the gizmo tag from your Cryptomattress under penalty of law.  Doing so will void your warranty :)

**Comment by fredrikaverpil** [comment]
> First, we're trying to stay backward compatible. Old 1.4.x scripts open with the 1.2 gizmos just fine.

This is good to know. And nice! 👍 

> Second, for putting Nuke scripts into cold storage where they should continue to work away from the warm light of the plugin, we made "decryptomatte". It replaces the gizmos with some expression nodes.

Aha, I shall have a quick look at that then when v1.2 stable is out.

> Fredrik, I just wanted to confirm that when you say it "breaks" you mean that you can no longer pull keys -- not that the output of a node that already had keys changes.

Correct.

> If you're converting nodes to Groups via a callback, you could probably add some logic [...]

Cryptomatte is already part of our software control system. So it's all under control and easy for artists to see which version of the Cryptomatte plugin was used when saving the Nuke script already :)
Thanks for the idea though!

> Doing so will void your warranty :)

Yes. We no longer touch the Cryptomatte nodes, leaving them as they are in the Nuke script.

Since Cryptomatte is gaining so much traction here :heart: I wanted to make sure that we won't have problems down if we start relying on it. And so I was just curious about the ability to make the Cryptomatte gizmo work even if converted into a group, detaching it from the external gizmo. However, now I know that was not the intention/design and I respect and appreciate that fully. It's just good to know your thoughts on the matter.

**Comment by jonahfriedman** [comment]
Ah, cool. Just to be clear, feel free to follow Andy's suggestion and I don't know of any reason that it wouldn't work.. but the "no warranty" thing from our license goes double. I'd recommend acquainting yourself with the test suite if you do that. 

Also, 1.2.0 is now available, enjoy!

**Comment by fredrikaverpil** [comment]
> Also, 1.2.0 is now available, enjoy!

Excellent, thank you!
