### ISSUE TITLE
[Nuke] Cryptomatte Gizmo - Decryptomatte

### ISSUE THREAD

**Issue by dgirondi** [Psyop/Cryptomatte#49]
Just wondering if there is any real need to create the ShuffleCopy there?

Wouldn't be cleaner to just set the proper output channels on the Expression node directly and get rid of the ShuffleCopy, Dot nodes and wonky node positioning there?

Even the possible Unpremult node could go away by adding de divide to the CryptoExpression directly on the Expression node.

Cheers,
Diogo

**Comment by jonahfriedman** [comment]
So if Andy and I remember correctly, the shufflecopy exists for what happens if you decryptomatte while using the "matte only" checkbox. It's only needed in that case (perhaps not even in that case at the cost of a little more complexity). 

I (tenatively) think we can say patches welcome here too. There are a few tests in the suite that check that decryptomatte does the right thing in various cases, any pull requests should ensure those tests continue to pass.

**Comment by dgirondi** [comment]
I'll give it a try.

Cheers!

**Comment by herronelou** [comment]
I've had a similar concern while decryptomatting a rather large script. I ended up grouping each mini-setup to keep the script clean.

**Comment by dgirondi** [comment]
The entire tree generated by the Decryptomatte could and and in my humble opinion should be turned into a single Expression node. Here I ended up re-writing that bit of the node in order to keep my scripts clean and inline work easy to manage.

I usually output crypto masks to the mask.a of a stream in Nuke, and work on inline blocks/sections from there onwards just re-assigning the mask.a channels as needed. 

![screen shot 2018-06-12 at 23 22 25](https://user-images.githubusercontent.com/519394/41327000-167e3bd0-6e98-11e8-84b1-8b7cbb05b036.png)

But perhaps I missing something and I'm completely wrong on my assumption regarding this.

**Comment by acjones** [comment]
I feel like this comes down to what the goals of Decryptomatte are.  For example, putting the unpremultiplication logic into the expression could certainly work, but the resulting mini script isn't quite as clear in what it's doing, or as easy to modify after the fact.

I think if we're revisiting Decryptomatte, it's worth considering what the overall goals are now that Cryptomatte is fairly well-known and open source.  In the beginning it was mainly present to allow for debugging in the unlikely event that something went wrong with Cryptomatte itself, and to allow scripts to be sent to facilities without the plugin installed (for example, before we open sourced it).  I think it's possible the priorities of how people would want to use this function are different now.

**Comment by jonahfriedman** [comment]
It does seem at least the simplest case - writing the extracted matte to a channel with no "unpremultiply" or "matte only", could just be a single node without changing the expression. Anyway, pull requests are still welcome here. 

The design goal of decryptomatte was that it would replicate all of the behavior of the gizmo, except the preview channels. Beyond that, I'd say a secondary design goal should be that it creates as little mess as possible. I think adhering to those design goals, it could be done better.

**Comment by jonahfriedman** [comment]
I have updated decryptomatte in what will soon be released as 1.2.1 (see the dev branch if you would like to try it). It now:

- creates only one expression node when it can, which can perform unpremultiply operations
- Makes a maximum of 3 nodes which are always in sequence (expression, remove, shuffle if matte-only is needed)
- Names the created nodes after the crypotomatte node ("Cryptomatte1" -> "Cryptomatte1Extract")
- Saves the matte list from the original gizmo onto a user knob on the expression node
- No dot

I think this should make everyone happy- in the case of an extraction to a custom channel, with unpremultiply, you get only one node. If you use "matte only" you get one more, and if you add "remove channels" you get one more still, and the matte list is saved so that you could pretty easily re-cryptomatte the whole setup if you were so inclined.

**Comment by jonahfriedman** [comment]
Was released in 1.2.1, closing old ticket.
