### ISSUE TITLE
[Nuke] Cryptomatte Gizmo - Unload Manifest

### ISSUE THREAD

**Issue by dgirondi** [Psyop/Cryptomatte#50]
Unloading a manifest should replicate some of the settings of the original node it was triggered from like "Preview", "Matte Only", "Remove Channels", "Matte Output" and "Unpremultiply". It should also use the current node for the first matte instead of creating new ones above the one you've triggered the "unload manifest".

Cheers,
Diogo

**Comment by jonahfriedman** [comment]
We talked it over and we don't actually agree with this one. The reasons are, 

- The use case imagined is just getting trying to get all the mattes, so the resulting nodes are set up to do only that.
- We leave the original node around because its where there might be actual work saved
- We don't like to make arbitrary changes. People don't like not finding things where they left them, so we try not to just change things without a clear benefit to a specific use case
- Unload manifest is a kind-of gimmicky feature that I think doesn't get a lot of use anyway, so this isn't terribly important

Thanks though.

**Comment by dgirondi** [comment]
Agreed, and fine by me.

Cheers,
Diogo

________________________________
