### ISSUE TITLE
[Nuke] 2.4 Gamma masks?

### ISSUE THREAD

**Issue by dgirondi** [Psyop/Cryptomatte#57]
I've been noticing a tiny little fringe around the edges of the generated masks from Nuke's Cryptomatte node in VRay renders that seems to be fixable by gamma correcting the masks to 2.4. 

Is that expected behavior or am I doing something completely wrong here?

Renders are from Maya's Vray (Lin float), Nuke 10.5v6 and the latest Cryptomatte master release.

I've just checked with a test image posted here by another user and the same things seems to happen there (file attached).

![cryptomatte_2 4-gamma](https://user-images.githubusercontent.com/519394/34148863-3383c904-e48a-11e7-82fe-1034f9b5d5c7.png)

Cheers,
Diogo

**Comment by jonahfriedman** [comment]
Hi @dgirondi,

I think all you're doing there is expanding the matte a little bit. You had a white pillow over blue here, try switching their colors and doing the color correction on the pillow, you may find you want to gamma down instead of up. 

If you want to make absolutely sure VRay is doing the right thing, render an RGB matte of the pillow as well and compare the edge pixel values.

**Comment by dgirondi** [comment]
Exactly, using either 2.4 or 1/2.4 tends to fix the problem. I just got interest on the magic number.

I have a job here where we have the exactly same element with both cryptomatte and multimatte and I'll do further comparisons.

Thanks!

________________________________

**Comment by jonahfriedman** [comment]
Cool, thanks. I kind of doubt there's anything special about that number. 

If there is an unexplained mismatch between the multimattes and cryptomatte output, that'd be at ticket for Chaos Group, but as far as I know there's no problem there.  

Thanks
