### ISSUE TITLE
Cryptomatte Nuke not picking up

### ISSUE THREAD

**Issue by janoschro** [Psyop/Cryptomatte#59]
hey guys,

Cryptomatte gizmo is not picking up my Vray pass.
I tried to modify the metadata. Like the photo below, but it`s not working.
Can anybody help me? Or you have a example scene for me?

Sorry I´m a Nuke noob.

Thank you.
![27660322-9ee83d86-5c0b-11e7-82d8-490087f86c29](https://user-images.githubusercontent.com/35375079/34915276-b516bab4-f923-11e7-9209-defd4adf248c.jpg)

**Comment by jonahfriedman** [comment]
You should not have to modify the metadata like that. For examples, there are some example EXR files included, so you can see how it should work. It's possible you saved this out of a renderview and that's why the metadata is not included, or something like that. 

Another thing to try- from your screenshot it looks like you aren't using the latest version of the Nuke plugins.

**Comment by jonahfriedman** [comment]
Feel free to reopen this if there actually is an issue with Nuke Cryptomatte. For support with VRay, I'd reach out to the VRay forums or chaos group.
