### ISSUE TITLE
Cryptomatte in AE is very slow !

### ISSUE THREAD

**Issue by NNois** [Psyop/Cryptomatte#93]
Hi,
Accustomed with the Nuke version I found the After Effect like, unusable. Are you seeing a 3/5 sec delay each frame?

**Comment by jonahfriedman** [comment]
Hi @NNois,

There is a separate repo for Fnordware's plugin, I'd suggest reporting issues and asking questions there. I know there was recent work performance, and some bugs to work around in how After Effects caches / reloads images.

**Comment by fnordware** [comment]
Did you also replace the OpenEXR file module, in addition to installing the Cryptomatte plug-in? (You have to do this again every time you update AE because it will put the old version of the OpenEXR plug-in back.) The updated OpenEXR file module greatly speeds up Cryptomatte vs. the one Adobe currently installs.

The plug-ins are [open source](https://gitlab.com/fnordware/ProEXR) if anyone want to try to make them faster.

That said, AE is just much slower than Nuke. It reads files slower, its multi-channel support is a bit of a hack and slower, its interactive rendering is much slower.
